### ISSUE TITLE
Have problem with Laravel 7.24

### ISSUE THREAD

**Issue by EricGerbers** [ArkEcosystem/laravel#25]
when install this package on Laravel 7.24 (latest version), it's show this error and cant continue install.
**Problem 1
    - Installation request for arkecosystem/laravel ^0.1.0 -> satisfiable by arkecosystem/laravel[0.1.0].
    - Conclusion: remove laravel/framework v7.24.0
    - Conclusion: don't install laravel/framework v7.24.0
    - arkecosystem/laravel 0.1.0 requires arkecosystem/client ^0.1.0 -> satisfiable by arkecosystem/client[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5].**

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
**Thanks for opening your first issue in the laravel repository!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
